name: Build & Test

on:
  push:
    branches: ["main", "rel-*"]

env:
  NAME: Soumya Subhrajit Bag
  AGE: 20

jobs:
  build:
    #  HERE YOU ARE TELLING THE WHERE YOU WANT TO RUN THE CODE..
    runs-on: ubuntu-20.04
    #  YOU CAN ADD MULTIPLE LANG VERSION FOR AUTOMATION TESTING..
    # RUNNER:
    #  RUNNER MEANS IS A BACIALLY OPRATING SYSTEM AND YOU CAN DO SELF-HOSTED RUNNERS
    timeout-minutes: 5

    steps:
      # ALWAYS GAVE A SPECIFIC NAME TO HELP THE IN THE DEBUGGING
      # WE CAN HAVE MULTIPLE OPARATING SYSYTEM.
      - name: Greet user
        run: echo "Hello $NAME"
